#!/usr/bin/env bash
# Builds BigTranscriber with GPU (Vulkan) acceleration. No system packages:
# uses the system Vulkan loader (libvulkan.so) + glslc, plus a project-local
# header-only Vulkan SDK that this script creates if missing.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"
SDK="$ROOT/.vulkan-sdk"

# 1) Ensure the local Vulkan header SDK exists.
if [[ ! -f "$SDK/include/vulkan/vulkan.h" ]]; then
  echo ">> Setting up local Vulkan header SDK ..."
  rm -rf "$SDK"; mkdir -p "$SDK/lib" "$SDK/bin"
  git clone --depth 1 https://github.com/KhronosGroup/Vulkan-Headers "$SDK/Vulkan-Headers"
  ln -sfn "$SDK/Vulkan-Headers/include" "$SDK/include"
  ln -sf "$(echo /usr/lib/libvulkan.so)" "$SDK/lib/libvulkan.so"
  ln -sf "$(command -v glslc)" "$SDK/bin/glslc"
fi

# Sanity: loader + shader compiler must be present (system-provided).
[[ -e /usr/lib/libvulkan.so ]] || { echo "libvulkan.so missing (install vulkan-icd-loader)"; exit 1; }
command -v glslc >/dev/null || { echo "glslc missing (install shaderc)"; exit 1; }

# 2) Keep src-tauri/.cargo/config.toml paths in sync with this machine.
cat > src-tauri/.cargo/config.toml <<EOF
# Auto-generated by scripts/build.sh — points the Vulkan build at the local SDK.
[env]
VULKAN_SDK = "$SDK"
CPATH = "$SDK/include"
BINDGEN_EXTRA_CLANG_ARGS = "-I$SDK/include"
EOF

# 3) Build (GPU/Vulkan via the `gpu` cargo feature).
echo ">> Building (release, Vulkan GPU) ..."
( cd src-tauri && cargo build --release --features gpu )
echo ">> Done: src-tauri/target/release/bigtranscriber"
